/* Institution costs and outcomes, imported from the US Department of
   Education's College Scorecard.

   Generated by scripts/import-scorecard.mjs — do not hand-edit. Re-run the
   importer instead, or the next import silently discards your changes.

   Scope: institutions predominantly awarding bachelor's degrees with 15,000 or
   more students AND a published net price. Places people search for by name,
   rather than thousands of thin pages nobody looks up.

   The figures are the Scorecard's "latest", which is not a single year — the
   Department publishes different metrics on different schedules, so net price
   and earnings may come from different cohorts. Every page using them says so,
   because it is exactly the caveat that matters when comparing two places. */
import type { Verified } from './types';

export interface College {
  id: number;
  name: string;
  slug: string;
  city: string;
  state: string;
  ownership: 'public' | 'private' | 'for-profit';
  /** published cost of attendance before any aid */
  sticker: number | null;
  /** average net price actually paid, after grant aid */
  netPrice: number;
  /** net price by family income band, where published */
  byIncome: {
    low: number | null; lowMid: number | null; mid: number | null;
    upperMid: number | null; high: number | null;
  };
  /** median earnings ten years after entry */
  earnings10: number | null;
  /** completion within 150% of normal time, four-year institutions */
  completion: number | null;
  size: number | null;
}

export const SCORECARD_VERIFIED: Verified = {
  checkedOn: '2026-09-02',
  source:
    'US Department of Education, College Scorecard API (api.data.gov), institution-level '
    + '"latest" data: cost of attendance, average net price and net price by family income, '
    + 'median earnings ten years after entry, and completion rate',
  by: 'BAMU',
};

export const COLLEGES: College[] = [
 {
  "id": 183026,
  "name": "Southern New Hampshire University",
  "slug": "southern-new-hampshire-university",
  "city": "Manchester",
  "state": "NH",
  "ownership": "private",
  "sticker": 40918,
  "netPrice": 36708,
  "byIncome": {
   "low": 36441,
   "lowMid": 36536,
   "mid": 36641,
   "upperMid": 37704,
   "high": 38025
  },
  "earnings10": 50318,
  "completion": 0.4283,
  "size": 163164
 },
 {
  "id": 433387,
  "name": "Western Governors University",
  "slug": "western-governors-university",
  "city": "Salt Lake City",
  "state": "UT",
  "ownership": "private",
  "sticker": 16728,
  "netPrice": 12548,
  "byIncome": {
   "low": 12064,
   "lowMid": 12436,
   "mid": 12578,
   "upperMid": 14824,
   "high": 12734
  },
  "earnings10": 60615,
  "completion": 0.4618,
  "size": 155088
 },
 {
  "id": 484613,
  "name": "University of Phoenix-Arizona",
  "slug": "university-of-phoenix-arizona",
  "city": "Phoenix",
  "state": "AZ",
  "ownership": "for-profit",
  "sticker": 19909,
  "netPrice": 13520,
  "byIncome": {
   "low": 12776,
   "lowMid": 13833,
   "mid": 14963,
   "upperMid": 17177,
   "high": 19150
  },
  "earnings10": 37752,
  "completion": 0.2084,
  "size": 85991
 },
 {
  "id": 104717,
  "name": "Grand Canyon University",
  "slug": "grand-canyon-university",
  "city": "Phoenix",
  "state": "AZ",
  "ownership": "private",
  "sticker": 32702,
  "netPrice": 22472,
  "byIncome": {
   "low": 18557,
   "lowMid": 18763,
   "mid": 21712,
   "upperMid": 24471,
   "high": 25701
  },
  "earnings10": 42186,
  "completion": 0.4346,
  "size": 73371
 },
 {
  "id": 104151,
  "name": "Arizona State University Campus Immersion",
  "slug": "arizona-state-university-campus-immersion",
  "city": "Tempe",
  "state": "AZ",
  "ownership": "public",
  "sticker": 30111,
  "netPrice": 14967,
  "byIncome": {
   "low": 9070,
   "lowMid": 10711,
   "mid": 16801,
   "upperMid": 20130,
   "high": 24296
  },
  "earnings10": 62668,
  "completion": 0.6804,
  "size": 64674
 },
 {
  "id": 228723,
  "name": "Texas A&M University-College Station",
  "slug": "texas-a-m-university-college-station",
  "city": "College Station",
  "state": "TX",
  "ownership": "public",
  "sticker": 32696,
  "netPrice": 21315,
  "byIncome": {
   "low": 12784,
   "lowMid": 13317,
   "mid": 17435,
   "upperMid": 26520,
   "high": 30660
  },
  "earnings10": 72097,
  "completion": 0.8391,
  "size": 59615
 },
 {
  "id": 132903,
  "name": "University of Central Florida",
  "slug": "university-of-central-florida",
  "city": "Orlando",
  "state": "FL",
  "ownership": "public",
  "sticker": 23133,
  "netPrice": 10411,
  "byIncome": {
   "low": 5816,
   "lowMid": 7174,
   "mid": 10128,
   "upperMid": 14902,
   "high": 17681
  },
  "earnings10": 58308,
  "completion": 0.7801,
  "size": 59146
 },
 {
  "id": 232557,
  "name": "Liberty University",
  "slug": "liberty-university",
  "city": "Lynchburg",
  "state": "VA",
  "ownership": "private",
  "sticker": 42025,
  "netPrice": 29357,
  "byIncome": {
   "low": 30667,
   "lowMid": 27807,
   "mid": 27347,
   "upperMid": 27142,
   "high": 30545
  },
  "earnings10": 44813,
  "completion": 0.6533,
  "size": 50012
 },
 {
  "id": 163204,
  "name": "University of Maryland Global Campus",
  "slug": "university-of-maryland-global-campus",
  "city": "Adelphi",
  "state": "MD",
  "ownership": "public",
  "sticker": 25400,
  "netPrice": 22063,
  "byIncome": {
   "low": 21830,
   "lowMid": 24400,
   "mid": 24400,
   "upperMid": null,
   "high": null
  },
  "earnings10": 65287,
  "completion": 0.3333,
  "size": 49664
 },
 {
  "id": 204796,
  "name": "Ohio State University-Main Campus",
  "slug": "ohio-state-university-main-campus",
  "city": "Columbus",
  "state": "OH",
  "ownership": "public",
  "sticker": 30305,
  "netPrice": 17339,
  "byIncome": {
   "low": 4885,
   "lowMid": 5751,
   "mid": 9807,
   "upperMid": 20461,
   "high": 27359
  },
  "earnings10": 60409,
  "completion": 0.8772,
  "size": 45638
 },
 {
  "id": 243780,
  "name": "Purdue University-Main Campus",
  "slug": "purdue-university-main-campus",
  "city": "West Lafayette",
  "state": "IN",
  "ownership": "public",
  "sticker": 24591,
  "netPrice": 14600,
  "byIncome": {
   "low": 5098,
   "lowMid": 6241,
   "mid": 9438,
   "upperMid": 18177,
   "high": 22742
  },
  "earnings10": 72424,
  "completion": 0.831,
  "size": 44503
 },
 {
  "id": 228778,
  "name": "The University of Texas at Austin",
  "slug": "the-university-of-texas-at-austin",
  "city": "Austin",
  "state": "TX",
  "ownership": "public",
  "sticker": 31247,
  "netPrice": 19857,
  "byIncome": {
   "low": 12553,
   "lowMid": 14297,
   "mid": 17207,
   "upperMid": 24406,
   "high": 30082
  },
  "earnings10": 75121,
  "completion": 0.889,
  "size": 42855
 },
 {
  "id": 104179,
  "name": "University of Arizona",
  "slug": "university-of-arizona",
  "city": "Tucson",
  "state": "AZ",
  "ownership": "public",
  "sticker": 29423,
  "netPrice": 16674,
  "byIncome": {
   "low": 13353,
   "lowMid": 14984,
   "mid": 16051,
   "upperMid": 19777,
   "high": 22307
  },
  "earnings10": 59979,
  "completion": 0.6752,
  "size": 42537
 },
 {
  "id": 214777,
  "name": "Pennsylvania State University-Main Campus",
  "slug": "pennsylvania-state-university-main-campus",
  "city": "University Park",
  "state": "PA",
  "ownership": "public",
  "sticker": 39694,
  "netPrice": 32875,
  "byIncome": {
   "low": 19845,
   "lowMid": 20049,
   "mid": 25667,
   "upperMid": 31834,
   "high": 37831
  },
  "earnings10": 63435,
  "completion": 0.8609,
  "size": 42284
 },
 {
  "id": 486840,
  "name": "Kennesaw State University",
  "slug": "kennesaw-state-university",
  "city": "Kennesaw",
  "state": "GA",
  "ownership": "public",
  "sticker": 24008,
  "netPrice": 15048,
  "byIncome": {
   "low": 12235,
   "lowMid": 12661,
   "mid": 15185,
   "upperMid": 18263,
   "high": 19309
  },
  "earnings10": 57552,
  "completion": 0.522,
  "size": 41254
 },
 {
  "id": 171100,
  "name": "Michigan State University",
  "slug": "michigan-state-university",
  "city": "East Lansing",
  "state": "MI",
  "ownership": "public",
  "sticker": 32198,
  "netPrice": 19680,
  "byIncome": {
   "low": 7068,
   "lowMid": 10830,
   "mid": 16521,
   "upperMid": 22703,
   "high": 28546
  },
  "earnings10": 67253,
  "completion": 0.8072,
  "size": 40922
 },
 {
  "id": 449339,
  "name": "American Public University System",
  "slug": "american-public-university-system",
  "city": "Charles Town",
  "state": "WV",
  "ownership": "for-profit",
  "sticker": 18768,
  "netPrice": 9597,
  "byIncome": {
   "low": 9335,
   "lowMid": 9766,
   "mid": 8951,
   "upperMid": 15559,
   "high": null
  },
  "earnings10": 44409,
  "completion": 0.5716,
  "size": 40074
 },
 {
  "id": 133951,
  "name": "Florida International University",
  "slug": "florida-international-university",
  "city": "Miami",
  "state": "FL",
  "ownership": "public",
  "sticker": 21462,
  "netPrice": 9288,
  "byIncome": {
   "low": 7003,
   "lowMid": 7873,
   "mid": 10925,
   "upperMid": 14568,
   "high": 18200
  },
  "earnings10": 60249,
  "completion": 0.7443,
  "size": 39508
 },
 {
  "id": 110565,
  "name": "California State University-Fullerton",
  "slug": "california-state-university-fullerton",
  "city": "Fullerton",
  "state": "CA",
  "ownership": "public",
  "sticker": 18269,
  "netPrice": 6555,
  "byIncome": {
   "low": 3315,
   "lowMid": 4123,
   "mid": 6090,
   "upperMid": 8930,
   "high": 15631
  },
  "earnings10": 62951,
  "completion": 0.7018,
  "size": 38546
 },
 {
  "id": 225511,
  "name": "University of Houston",
  "slug": "university-of-houston",
  "city": "Houston",
  "state": "TX",
  "ownership": "public",
  "sticker": 26185,
  "netPrice": 14276,
  "byIncome": {
   "low": 10929,
   "lowMid": 10220,
   "mid": 12528,
   "upperMid": 19197,
   "high": 23811
  },
  "earnings10": 62377,
  "completion": 0.6456,
  "size": 38380
 },
 {
  "id": 151351,
  "name": "Indiana University-Bloomington",
  "slug": "indiana-university-bloomington",
  "city": "Bloomington",
  "state": "IN",
  "ownership": "public",
  "sticker": 28801,
  "netPrice": 16264,
  "byIncome": {
   "low": 6324,
   "lowMid": 7610,
   "mid": 12154,
   "upperMid": 20204,
   "high": 25128
  },
  "earnings10": 63742,
  "completion": 0.8021,
  "size": 37806
 },
 {
  "id": 186380,
  "name": "Rutgers University-New Brunswick",
  "slug": "rutgers-university-new-brunswick",
  "city": "New Brunswick",
  "state": "NJ",
  "ownership": "public",
  "sticker": 36993,
  "netPrice": 24406,
  "byIncome": {
   "low": 16343,
   "lowMid": 16210,
   "mid": 18282,
   "upperMid": 25106,
   "high": 35016
  },
  "earnings10": 74479,
  "completion": 0.8363,
  "size": 37751
 },
 {
  "id": 137351,
  "name": "University of South Florida",
  "slug": "university-of-south-florida",
  "city": "Tampa",
  "state": "FL",
  "ownership": "public",
  "sticker": 22859,
  "netPrice": 9812,
  "byIncome": {
   "low": 4122,
   "lowMid": 5444,
   "mid": 9326,
   "upperMid": 15224,
   "high": 18497
  },
  "earnings10": 57743,
  "completion": 0.7676,
  "size": 37207
 },
 {
  "id": 240444,
  "name": "University of Wisconsin-Madison",
  "slug": "university-of-wisconsin-madison",
  "city": "Madison",
  "state": "WI",
  "ownership": "public",
  "sticker": 28679,
  "netPrice": 17354,
  "byIncome": {
   "low": 4200,
   "lowMid": 4101,
   "mid": 8134,
   "upperMid": 17763,
   "high": 27292
  },
  "earnings10": 73792,
  "completion": 0.8955,
  "size": 36902
 },
 {
  "id": 145637,
  "name": "University of Illinois Urbana-Champaign",
  "slug": "university-of-illinois-urbana-champaign",
  "city": "Champaign",
  "state": "IL",
  "ownership": "public",
  "sticker": 33642,
  "netPrice": 14355,
  "byIncome": {
   "low": 2038,
   "lowMid": 5373,
   "mid": 7982,
   "upperMid": 15152,
   "high": 28761
  },
  "earnings10": 81054,
  "completion": 0.8513,
  "size": 36258
 },
 {
  "id": 228459,
  "name": "Texas State University",
  "slug": "texas-state-university",
  "city": "San Marcos",
  "state": "TX",
  "ownership": "public",
  "sticker": 28073,
  "netPrice": 16805,
  "byIncome": {
   "low": 12715,
   "lowMid": 13557,
   "mid": 13804,
   "upperMid": 20028,
   "high": 24713
  },
  "earnings10": 56906,
  "completion": 0.5528,
  "size": 36177
 },
 {
  "id": 110583,
  "name": "California State University-Long Beach",
  "slug": "california-state-university-long-beach",
  "city": "Long Beach",
  "state": "CA",
  "ownership": "public",
  "sticker": 22679,
  "netPrice": 10440,
  "byIncome": {
   "low": 7183,
   "lowMid": 7831,
   "mid": 9705,
   "upperMid": 12630,
   "high": 19750
  },
  "earnings10": 64403,
  "completion": 0.6888,
  "size": 35924
 },
 {
  "id": 134130,
  "name": "University of Florida",
  "slug": "university-of-florida",
  "city": "Gainesville",
  "state": "FL",
  "ownership": "public",
  "sticker": 22523,
  "netPrice": 6541,
  "byIncome": {
   "low": 1982,
   "lowMid": 2768,
   "mid": 7151,
   "upperMid": 12905,
   "high": 16723
  },
  "earnings10": 71588,
  "completion": 0.9112,
  "size": 35629
 },
 {
  "id": 122409,
  "name": "San Diego State University",
  "slug": "san-diego-state-university",
  "city": "San Diego",
  "state": "CA",
  "ownership": "public",
  "sticker": 27780,
  "netPrice": 15364,
  "byIncome": {
   "low": 9910,
   "lowMid": 10017,
   "mid": 12697,
   "upperMid": 15891,
   "high": 23821
  },
  "earnings10": 64909,
  "completion": 0.7643,
  "size": 35377
 },
 {
  "id": 110680,
  "name": "University of California-San Diego",
  "slug": "university-of-california-san-diego",
  "city": "La Jolla",
  "state": "CA",
  "ownership": "public",
  "sticker": 38701,
  "netPrice": 12470,
  "byIncome": {
   "low": 7525,
   "lowMid": 8155,
   "mid": 9942,
   "upperMid": 15199,
   "high": 28785
  },
  "earnings10": 84943,
  "completion": 0.8605,
  "size": 34948
 },
 {
  "id": 227216,
  "name": "University of North Texas",
  "slug": "university-of-north-texas",
  "city": "Denton",
  "state": "TX",
  "ownership": "public",
  "sticker": 26243,
  "netPrice": 15649,
  "byIncome": {
   "low": 12311,
   "lowMid": 12668,
   "mid": 14473,
   "upperMid": 19576,
   "high": 22943
  },
  "earnings10": 57010,
  "completion": 0.6071,
  "size": 34341
 },
 {
  "id": 170976,
  "name": "University of Michigan-Ann Arbor",
  "slug": "university-of-michigan-ann-arbor",
  "city": "Ann Arbor",
  "state": "MI",
  "ownership": "public",
  "sticker": 34654,
  "netPrice": 13138,
  "byIncome": {
   "low": 1043,
   "lowMid": 1878,
   "mid": 4895,
   "upperMid": 10869,
   "high": 26517
  },
  "earnings10": 83648,
  "completion": 0.932,
  "size": 34177
 },
 {
  "id": 110662,
  "name": "University of California-Los Angeles",
  "slug": "university-of-california-los-angeles",
  "city": "Los Angeles",
  "state": "CA",
  "ownership": "public",
  "sticker": 38614,
  "netPrice": 12548,
  "byIncome": {
   "low": 5579,
   "lowMid": 6682,
   "mid": 9811,
   "upperMid": 14142,
   "high": 29682
  },
  "earnings10": 82511,
  "completion": 0.9262,
  "size": 33475
 },
 {
  "id": 100751,
  "name": "The University of Alabama",
  "slug": "the-university-of-alabama",
  "city": "Tuscaloosa",
  "state": "AL",
  "ownership": "public",
  "sticker": 33382,
  "netPrice": 22420,
  "byIncome": {
   "low": 19169,
   "lowMid": 19884,
   "mid": 22258,
   "upperMid": 25658,
   "high": 26729
  },
  "earnings10": 59221,
  "completion": 0.7337,
  "size": 33227
 },
 {
  "id": 110635,
  "name": "University of California-Berkeley",
  "slug": "university-of-california-berkeley",
  "city": "Berkeley",
  "state": "CA",
  "ownership": "public",
  "sticker": 45619,
  "netPrice": 13481,
  "byIncome": {
   "low": 5311,
   "lowMid": 6501,
   "mid": 9693,
   "upperMid": 15074,
   "high": 34529
  },
  "earnings10": 92446,
  "completion": 0.9284,
  "size": 33068
 },
 {
  "id": 230038,
  "name": "Brigham Young University",
  "slug": "brigham-young-university",
  "city": "Provo",
  "state": "UT",
  "ownership": "private",
  "sticker": 22690,
  "netPrice": 15564,
  "byIncome": {
   "low": 10444,
   "lowMid": 10112,
   "mid": 13062,
   "upperMid": 16378,
   "high": 20542
  },
  "earnings10": 75790,
  "completion": 0.8098,
  "size": 32952
 },
 {
  "id": 110608,
  "name": "California State University-Northridge",
  "slug": "california-state-university-northridge",
  "city": "Northridge",
  "state": "CA",
  "ownership": "public",
  "sticker": 20485,
  "netPrice": 7021,
  "byIncome": {
   "low": 4905,
   "lowMid": 5450,
   "mid": 7744,
   "upperMid": 11262,
   "high": 18040
  },
  "earnings10": 59115,
  "completion": 0.5695,
  "size": 32691
 },
 {
  "id": 229115,
  "name": "Texas Tech University",
  "slug": "texas-tech-university",
  "city": "Lubbock",
  "state": "TX",
  "ownership": "public",
  "sticker": 27443,
  "netPrice": 19070,
  "byIncome": {
   "low": 12457,
   "lowMid": 13851,
   "mid": 17058,
   "upperMid": 22073,
   "high": 24622
  },
  "earnings10": 62454,
  "completion": 0.6869,
  "size": 32394
 },
 {
  "id": 228769,
  "name": "The University of Texas at Arlington",
  "slug": "the-university-of-texas-at-arlington",
  "city": "Arlington",
  "state": "TX",
  "ownership": "public",
  "sticker": 25261,
  "netPrice": 13951,
  "byIncome": {
   "low": 11893,
   "lowMid": 12003,
   "mid": 12612,
   "upperMid": 16371,
   "high": 24692
  },
  "earnings10": 63199,
  "completion": 0.5402,
  "size": 32294
 },
 {
  "id": 110644,
  "name": "University of California-Davis",
  "slug": "university-of-california-davis",
  "city": "Davis",
  "state": "CA",
  "ownership": "public",
  "sticker": 41238,
  "netPrice": 14741,
  "byIncome": {
   "low": 9211,
   "lowMid": 9966,
   "mid": 11951,
   "upperMid": 16294,
   "high": 31272
  },
  "earnings10": 80838,
  "completion": 0.8567,
  "size": 32253
 },
 {
  "id": 134097,
  "name": "Florida State University",
  "slug": "florida-state-university",
  "city": "Tallahassee",
  "state": "FL",
  "ownership": "public",
  "sticker": 25720,
  "netPrice": 11297,
  "byIncome": {
   "low": 5938,
   "lowMid": 6963,
   "mid": 10496,
   "upperMid": 14991,
   "high": 19239
  },
  "earnings10": 61675,
  "completion": 0.8561,
  "size": 32212
 },
 {
  "id": 139959,
  "name": "University of Georgia",
  "slug": "university-of-georgia",
  "city": "Athens",
  "state": "GA",
  "ownership": "public",
  "sticker": 27993,
  "netPrice": 13936,
  "byIncome": {
   "low": 8085,
   "lowMid": 8686,
   "mid": 13096,
   "upperMid": 16942,
   "high": 18079
  },
  "earnings10": 68726,
  "completion": 0.8969,
  "size": 32137
 },
 {
  "id": 236948,
  "name": "University of Washington-Seattle Campus",
  "slug": "university-of-washington-seattle-campus",
  "city": "Seattle",
  "state": "WA",
  "ownership": "public",
  "sticker": 32446,
  "netPrice": 14091,
  "byIncome": {
   "low": 6384,
   "lowMid": 7039,
   "mid": 8110,
   "upperMid": 14328,
   "high": 30019
  },
  "earnings10": 78466,
  "completion": 0.8518,
  "size": 31942
 },
 {
  "id": 126614,
  "name": "University of Colorado Boulder",
  "slug": "university-of-colorado-boulder",
  "city": "Boulder",
  "state": "CO",
  "ownership": "public",
  "sticker": 37684,
  "netPrice": 25346,
  "byIncome": {
   "low": 14231,
   "lowMid": 14381,
   "mid": 18828,
   "upperMid": 26915,
   "high": 34818
  },
  "earnings10": 69738,
  "completion": 0.7419,
  "size": 31939
 },
 {
  "id": 174066,
  "name": "University of Minnesota-Twin Cities",
  "slug": "university-of-minnesota-twin-cities",
  "city": "Minneapolis",
  "state": "MN",
  "ownership": "public",
  "sticker": 30061,
  "netPrice": 16778,
  "byIncome": {
   "low": 6642,
   "lowMid": 7283,
   "mid": 9931,
   "upperMid": 16415,
   "high": 27008
  },
  "earnings10": 69020,
  "completion": 0.8528,
  "size": 31855
 },
 {
  "id": 233921,
  "name": "Virginia Polytechnic Institute and State University",
  "slug": "virginia-polytechnic-institute-and-state-university",
  "city": "Blacksburg",
  "state": "VA",
  "ownership": "public",
  "sticker": 36951,
  "netPrice": 24953,
  "byIncome": {
   "low": 11689,
   "lowMid": 11670,
   "mid": 17894,
   "upperMid": 25835,
   "high": 34201
  },
  "earnings10": 81698,
  "completion": 0.8622,
  "size": 30923
 },
 {
  "id": 163286,
  "name": "University of Maryland-College Park",
  "slug": "university-of-maryland-college-park",
  "city": "College Park",
  "state": "MD",
  "ownership": "public",
  "sticker": 29299,
  "netPrice": 15678,
  "byIncome": {
   "low": 2962,
   "lowMid": 6051,
   "mid": 10273,
   "upperMid": 18250,
   "high": 26691
  },
  "earnings10": 82860,
  "completion": 0.8859,
  "size": 30760
 },
 {
  "id": 209542,
  "name": "Oregon State University",
  "slug": "oregon-state-university",
  "city": "Corvallis",
  "state": "OR",
  "ownership": "public",
  "sticker": 31653,
  "netPrice": 19604,
  "byIncome": {
   "low": 12107,
   "lowMid": 13036,
   "mid": 15729,
   "upperMid": 20262,
   "high": 27459
  },
  "earnings10": 64010,
  "completion": 0.7011,
  "size": 30743
 },
 {
  "id": 159391,
  "name": "Louisiana State University and Agricultural & Mechanical College",
  "slug": "louisiana-state-university-and-agricultural-mechanical-college",
  "city": "Baton Rouge",
  "state": "LA",
  "ownership": "public",
  "sticker": 34705,
  "netPrice": 19151,
  "byIncome": {
   "low": 13056,
   "lowMid": 15696,
   "mid": 20223,
   "upperMid": 23878,
   "high": 26489
  },
  "earnings10": 61251,
  "completion": 0.6881,
  "size": 30594
 },
 {
  "id": 229027,
  "name": "The University of Texas at San Antonio",
  "slug": "the-university-of-texas-at-san-antonio",
  "city": "San Antonio",
  "state": "TX",
  "ownership": "public",
  "sticker": 22352,
  "netPrice": 10836,
  "byIncome": {
   "low": 7870,
   "lowMid": 7847,
   "mid": 9172,
   "upperMid": 15446,
   "high": 20489
  },
  "earnings10": 57131,
  "completion": 0.5264,
  "size": 30580
 },
 {
  "id": 221759,
  "name": "The University of Tennessee-Knoxville",
  "slug": "the-university-of-tennessee-knoxville",
  "city": "Knoxville",
  "state": "TN",
  "ownership": "public",
  "sticker": 33678,
  "netPrice": 18976,
  "byIncome": {
   "low": 10029,
   "lowMid": 12162,
   "mid": 18206,
   "upperMid": 23627,
   "high": 25688
  },
  "earnings10": 60249,
  "completion": 0.7392,
  "size": 30418
 },
 {
  "id": 110653,
  "name": "University of California-Irvine",
  "slug": "university-of-california-irvine",
  "city": "Irvine",
  "state": "CA",
  "ownership": "public",
  "sticker": 38632,
  "netPrice": 14251,
  "byIncome": {
   "low": 8123,
   "lowMid": 9313,
   "mid": 11642,
   "upperMid": 15164,
   "high": 30546
  },
  "earnings10": 80735,
  "completion": 0.8687,
  "size": 30197
 },
 {
  "id": 201885,
  "name": "University of Cincinnati-Main Campus",
  "slug": "university-of-cincinnati-main-campus",
  "city": "Cincinnati",
  "state": "OH",
  "ownership": "public",
  "sticker": 32171,
  "netPrice": 25648,
  "byIncome": {
   "low": 17974,
   "lowMid": 18092,
   "mid": 22492,
   "upperMid": 27596,
   "high": 29616
  },
  "earnings10": 54810,
  "completion": 0.7496,
  "size": 29882
 },
 {
  "id": 218663,
  "name": "University of South Carolina-Columbia",
  "slug": "university-of-south-carolina-columbia",
  "city": "Columbia",
  "state": "SC",
  "ownership": "public",
  "sticker": 31638,
  "netPrice": 22811,
  "byIncome": {
   "low": 12634,
   "lowMid": 14953,
   "mid": 19859,
   "upperMid": 24478,
   "high": 28125
  },
  "earnings10": 62177,
  "completion": 0.7882,
  "size": 29820
 },
 {
  "id": 106397,
  "name": "University of Arkansas",
  "slug": "university-of-arkansas",
  "city": "Fayetteville",
  "state": "AR",
  "ownership": "public",
  "sticker": 27767,
  "netPrice": 18209,
  "byIncome": {
   "low": 14319,
   "lowMid": 14322,
   "mid": 15934,
   "upperMid": 20772,
   "high": 22470
  },
  "earnings10": 58191,
  "completion": 0.7052,
  "size": 28677
 },
 {
  "id": 227368,
  "name": "The University of Texas Rio Grande Valley",
  "slug": "the-university-of-texas-rio-grande-valley",
  "city": "Edinburg",
  "state": "TX",
  "ownership": "public",
  "sticker": 16830,
  "netPrice": 4831,
  "byIncome": {
   "low": 3785,
   "lowMid": 3877,
   "mid": 5665,
   "upperMid": 7972,
   "high": 13782
  },
  "earnings10": 49620,
  "completion": 0.509,
  "size": 28666
 },
 {
  "id": 193900,
  "name": "New York University",
  "slug": "new-york-university",
  "city": "New York",
  "state": "NY",
  "ownership": "private",
  "sticker": 84374,
  "netPrice": 37050,
  "byIncome": {
   "low": 16977,
   "lowMid": 14017,
   "mid": 16862,
   "upperMid": 32766,
   "high": 66876
  },
  "earnings10": 82509,
  "completion": 0.8757,
  "size": 28663
 },
 {
  "id": 110617,
  "name": "California State University-Sacramento",
  "slug": "california-state-university-sacramento",
  "city": "Sacramento",
  "state": "CA",
  "ownership": "public",
  "sticker": 22945,
  "netPrice": 9338,
  "byIncome": {
   "low": 6501,
   "lowMid": 7001,
   "mid": 9212,
   "upperMid": 11814,
   "high": 18861
  },
  "earnings10": 64876,
  "completion": 0.5629,
  "size": 28350
 },
 {
  "id": 126827,
  "name": "Colorado Technical University-Colorado Springs",
  "slug": "colorado-technical-university-colorado-springs",
  "city": "Colorado Springs",
  "state": "CO",
  "ownership": "for-profit",
  "sticker": 23744,
  "netPrice": 16745,
  "byIncome": {
   "low": 16474,
   "lowMid": 16990,
   "mid": 18404,
   "upperMid": 22215,
   "high": 22394
  },
  "earnings10": 37180,
  "completion": 0.1878,
  "size": 28086
 },
 {
  "id": 232186,
  "name": "George Mason University",
  "slug": "george-mason-university",
  "city": "Fairfax",
  "state": "VA",
  "ownership": "public",
  "sticker": 28604,
  "netPrice": 17915,
  "byIncome": {
   "low": 11942,
   "lowMid": 12093,
   "mid": 15224,
   "upperMid": 19430,
   "high": 25894
  },
  "earnings10": 76343,
  "completion": 0.6784,
  "size": 27752
 },
 {
  "id": 122755,
  "name": "San Jose State University",
  "slug": "san-jose-state-university",
  "city": "San Jose",
  "state": "CA",
  "ownership": "public",
  "sticker": 26593,
  "netPrice": 13760,
  "byIncome": {
   "low": 9730,
   "lowMid": 10114,
   "mid": 12099,
   "upperMid": 15102,
   "high": 22862
  },
  "earnings10": 78988,
  "completion": 0.6922,
  "size": 27601
 },
 {
  "id": 199193,
  "name": "North Carolina State University at Raleigh",
  "slug": "north-carolina-state-university-at-raleigh",
  "city": "Raleigh",
  "state": "NC",
  "ownership": "public",
  "sticker": 26425,
  "netPrice": 17303,
  "byIncome": {
   "low": 6382,
   "lowMid": 8758,
   "mid": 13334,
   "upperMid": 20087,
   "high": 24652
  },
  "earnings10": 68758,
  "completion": 0.8476,
  "size": 27371
 },
 {
  "id": 230764,
  "name": "University of Utah",
  "slug": "university-of-utah",
  "city": "Salt Lake City",
  "state": "UT",
  "ownership": "public",
  "sticker": 25557,
  "netPrice": 16200,
  "byIncome": {
   "low": 13123,
   "lowMid": 13424,
   "mid": 14246,
   "upperMid": 17663,
   "high": 21533
  },
  "earnings10": 67170,
  "completion": 0.6505,
  "size": 27264
 },
 {
  "id": 100858,
  "name": "Auburn University",
  "slug": "auburn-university",
  "city": "Auburn",
  "state": "AL",
  "ownership": "public",
  "sticker": 34919,
  "netPrice": 24323,
  "byIncome": {
   "low": 16681,
   "lowMid": 17627,
   "mid": 20558,
   "upperMid": 25808,
   "high": 29547
  },
  "earnings10": 65337,
  "completion": 0.8195,
  "size": 26816
 },
 {
  "id": 139940,
  "name": "Georgia State University",
  "slug": "georgia-state-university",
  "city": "Atlanta",
  "state": "GA",
  "ownership": "public",
  "sticker": 28241,
  "netPrice": 15931,
  "byIncome": {
   "low": 13787,
   "lowMid": 14430,
   "mid": 16656,
   "upperMid": 19390,
   "high": 20305
  },
  "earnings10": 47384,
  "completion": 0.5306,
  "size": 26623
 },
 {
  "id": 134237,
  "name": "Full Sail University",
  "slug": "full-sail-university",
  "city": "Winter Park",
  "state": "FL",
  "ownership": "for-profit",
  "sticker": 47530,
  "netPrice": 38875,
  "byIncome": {
   "low": 38738,
   "lowMid": 38162,
   "mid": 38181,
   "upperMid": 40236,
   "high": 41762
  },
  "earnings10": 38219,
  "completion": 0.4433,
  "size": 25777
 },
 {
  "id": 126818,
  "name": "Colorado State University-Fort Collins",
  "slug": "colorado-state-university-fort-collins",
  "city": "Fort Collins",
  "state": "CO",
  "ownership": "public",
  "sticker": 31642,
  "netPrice": 21279,
  "byIncome": {
   "low": 13259,
   "lowMid": 14460,
   "mid": 15905,
   "upperMid": 21927,
   "high": 29763
  },
  "earnings10": 60543,
  "completion": 0.6651,
  "size": 25538
 },
 {
  "id": 153603,
  "name": "Iowa State University",
  "slug": "iowa-state-university",
  "city": "Ames",
  "state": "IA",
  "ownership": "public",
  "sticker": 24018,
  "netPrice": 18589,
  "byIncome": {
   "low": 10582,
   "lowMid": 11506,
   "mid": 15463,
   "upperMid": 19605,
   "high": 22496
  },
  "earnings10": 63386,
  "completion": 0.7532,
  "size": 25367
 },
 {
  "id": 110529,
  "name": "California State Polytechnic University-Pomona",
  "slug": "california-state-polytechnic-university-pomona",
  "city": "Pomona",
  "state": "CA",
  "ownership": "public",
  "sticker": 23955,
  "netPrice": 11531,
  "byIncome": {
   "low": 7851,
   "lowMid": 8433,
   "mid": 10734,
   "upperMid": 13894,
   "high": 20716
  },
  "earnings10": 71902,
  "completion": 0.6843,
  "size": 25042
 },
 {
  "id": 157085,
  "name": "University of Kentucky",
  "slug": "university-of-kentucky",
  "city": "Lexington",
  "state": "KY",
  "ownership": "public",
  "sticker": 34391,
  "netPrice": 18851,
  "byIncome": {
   "low": 12182,
   "lowMid": 12119,
   "mid": 16313,
   "upperMid": 21192,
   "high": 26781
  },
  "earnings10": 59025,
  "completion": 0.7142,
  "size": 24763
 },
 {
  "id": 182281,
  "name": "University of Nevada-Las Vegas",
  "slug": "university-of-nevada-las-vegas",
  "city": "Las Vegas",
  "state": "NV",
  "ownership": "public",
  "sticker": 19638,
  "netPrice": 10359,
  "byIncome": {
   "low": 8526,
   "lowMid": 8537,
   "mid": 10606,
   "upperMid": 13513,
   "high": 15905
  },
  "earnings10": 55037,
  "completion": 0.5051,
  "size": 24622
 },
 {
  "id": 199139,
  "name": "University of North Carolina at Charlotte",
  "slug": "university-of-north-carolina-at-charlotte",
  "city": "Charlotte",
  "state": "NC",
  "ownership": "public",
  "sticker": 23010,
  "netPrice": 15435,
  "byIncome": {
   "low": 10357,
   "lowMid": 10668,
   "mid": 13690,
   "upperMid": 19822,
   "high": 21761
  },
  "earnings10": 57289,
  "completion": 0.6897,
  "size": 24453
 },
 {
  "id": 178396,
  "name": "University of Missouri-Columbia",
  "slug": "university-of-missouri-columbia",
  "city": "Columbia",
  "state": "MO",
  "ownership": "public",
  "sticker": 31713,
  "netPrice": 20268,
  "byIncome": {
   "low": 13841,
   "lowMid": 13378,
   "mid": 13722,
   "upperMid": 19762,
   "high": 26304
  },
  "earnings10": 63403,
  "completion": 0.7494,
  "size": 23929
 },
 {
  "id": 133669,
  "name": "Florida Atlantic University",
  "slug": "florida-atlantic-university",
  "city": "Boca Raton",
  "state": "FL",
  "ownership": "public",
  "sticker": 21522,
  "netPrice": 8752,
  "byIncome": {
   "low": 3022,
   "lowMid": 4135,
   "mid": 8106,
   "upperMid": 14440,
   "high": 16854
  },
  "earnings10": 56746,
  "completion": 0.6257,
  "size": 23757
 },
 {
  "id": 166629,
  "name": "University of Massachusetts-Amherst",
  "slug": "university-of-massachusetts-amherst",
  "city": "Amherst",
  "state": "MA",
  "ownership": "public",
  "sticker": 34549,
  "netPrice": 22383,
  "byIncome": {
   "low": 10164,
   "lowMid": 10456,
   "mid": 12932,
   "upperMid": 18964,
   "high": 30793
  },
  "earnings10": 71631,
  "completion": 0.8326,
  "size": 23671
 },
 {
  "id": 217882,
  "name": "Clemson University",
  "slug": "clemson-university",
  "city": "Clemson",
  "state": "SC",
  "ownership": "public",
  "sticker": 35015,
  "netPrice": 22253,
  "byIncome": {
   "low": 13607,
   "lowMid": 14109,
   "mid": 18851,
   "upperMid": 24833,
   "high": 27922
  },
  "earnings10": 71513,
  "completion": 0.8656,
  "size": 23300
 },
 {
  "id": 110705,
  "name": "University of California-Santa Barbara",
  "slug": "university-of-california-santa-barbara",
  "city": "Santa Barbara",
  "state": "CA",
  "ownership": "public",
  "sticker": 41573,
  "netPrice": 16109,
  "byIncome": {
   "low": 9231,
   "lowMid": 9992,
   "mid": 12588,
   "upperMid": 17136,
   "high": 31863
  },
  "earnings10": 74915,
  "completion": 0.8303,
  "size": 23113
 },
 {
  "id": 105330,
  "name": "Northern Arizona University",
  "slug": "northern-arizona-university",
  "city": "Flagstaff",
  "state": "AZ",
  "ownership": "public",
  "sticker": 29933,
  "netPrice": 14158,
  "byIncome": {
   "low": 9709,
   "lowMid": 10398,
   "mid": 13330,
   "upperMid": 18050,
   "high": 20686
  },
  "earnings10": 54384,
  "completion": 0.6132,
  "size": 22903
 },
 {
  "id": 207500,
  "name": "University of Oklahoma-Norman Campus",
  "slug": "university-of-oklahoma-norman-campus",
  "city": "Norman",
  "state": "OK",
  "ownership": "public",
  "sticker": 28872,
  "netPrice": 15300,
  "byIncome": {
   "low": 10509,
   "lowMid": 10602,
   "mid": 14536,
   "upperMid": 19342,
   "high": 20986
  },
  "earnings10": 63126,
  "completion": 0.7533,
  "size": 22734
 },
 {
  "id": 110671,
  "name": "University of California-Riverside",
  "slug": "university-of-california-riverside",
  "city": "Riverside",
  "state": "CA",
  "ownership": "public",
  "sticker": 38942,
  "netPrice": 14304,
  "byIncome": {
   "low": 8852,
   "lowMid": 9840,
   "mid": 13111,
   "upperMid": 16571,
   "high": 30393
  },
  "earnings10": 67699,
  "completion": 0.7596,
  "size": 22593
 },
 {
  "id": 153658,
  "name": "University of Iowa",
  "slug": "university-of-iowa",
  "city": "Iowa City",
  "state": "IA",
  "ownership": "public",
  "sticker": 28596,
  "netPrice": 22531,
  "byIncome": {
   "low": 15316,
   "lowMid": 15489,
   "mid": 19930,
   "upperMid": 23811,
   "high": 26266
  },
  "earnings10": 64762,
  "completion": 0.7463,
  "size": 22264
 },
 {
  "id": 145600,
  "name": "University of Illinois Chicago",
  "slug": "university-of-illinois-chicago",
  "city": "Chicago",
  "state": "IL",
  "ownership": "public",
  "sticker": 27521,
  "netPrice": 10974,
  "byIncome": {
   "low": 7529,
   "lowMid": 8119,
   "mid": 10921,
   "upperMid": 16185,
   "high": 25047
  },
  "earnings10": 68740,
  "completion": 0.6162,
  "size": 22170
 },
 {
  "id": 110422,
  "name": "California Polytechnic State University-San Luis Obispo",
  "slug": "california-polytechnic-state-university-san-luis-obispo",
  "city": "San Luis Obispo",
  "state": "CA",
  "ownership": "public",
  "sticker": 32265,
  "netPrice": 16665,
  "byIncome": {
   "low": 7529,
   "lowMid": 7253,
   "mid": 9896,
   "upperMid": 15786,
   "high": 27772
  },
  "earnings10": 90768,
  "completion": 0.864,
  "size": 21996
 },
 {
  "id": 139931,
  "name": "Georgia Southern University",
  "slug": "georgia-southern-university",
  "city": "Statesboro",
  "state": "GA",
  "ownership": "public",
  "sticker": 24430,
  "netPrice": 15267,
  "byIncome": {
   "low": 12162,
   "lowMid": 12564,
   "mid": 14965,
   "upperMid": 18408,
   "high": 19789
  },
  "earnings10": 53236,
  "completion": 0.549,
  "size": 21790
 },
 {
  "id": 207388,
  "name": "Oklahoma State University-Main Campus",
  "slug": "oklahoma-state-university-main-campus",
  "city": "Stillwater",
  "state": "OK",
  "ownership": "public",
  "sticker": 28290,
  "netPrice": 17447,
  "byIncome": {
   "low": 12243,
   "lowMid": 12314,
   "mid": 15893,
   "upperMid": 21896,
   "high": 24711
  },
  "earnings10": 57413,
  "completion": 0.6817,
  "size": 21773
 },
 {
  "id": 228787,
  "name": "The University of Texas at Dallas",
  "slug": "the-university-of-texas-at-dallas",
  "city": "Richardson",
  "state": "TX",
  "ownership": "public",
  "sticker": 29807,
  "netPrice": 18267,
  "byIncome": {
   "low": 12814,
   "lowMid": 13510,
   "mid": 14030,
   "upperMid": 19892,
   "high": 26596
  },
  "earnings10": 68227,
  "completion": 0.7569,
  "size": 21751
 },
 {
  "id": 110556,
  "name": "California State University-Fresno",
  "slug": "california-state-university-fresno",
  "city": "Fresno",
  "state": "CA",
  "ownership": "public",
  "sticker": 20095,
  "netPrice": 7000,
  "byIncome": {
   "low": 5105,
   "lowMid": 5429,
   "mid": 7196,
   "upperMid": 10291,
   "high": 16899
  },
  "earnings10": 61244,
  "completion": 0.5696,
  "size": 21605
 },
 {
  "id": 176017,
  "name": "University of Mississippi",
  "slug": "university-of-mississippi",
  "city": "University",
  "state": "MS",
  "ownership": "public",
  "sticker": 28660,
  "netPrice": 13314,
  "byIncome": {
   "low": 8945,
   "lowMid": 9217,
   "mid": 14794,
   "upperMid": 18573,
   "high": 21313
  },
  "earnings10": 50994,
  "completion": 0.7174,
  "size": 21473
 },
 {
  "id": 155317,
  "name": "University of Kansas",
  "slug": "university-of-kansas",
  "city": "Lawrence",
  "state": "KS",
  "ownership": "public",
  "sticker": 26751,
  "netPrice": 18059,
  "byIncome": {
   "low": 12544,
   "lowMid": 12942,
   "mid": 15154,
   "upperMid": 19169,
   "high": 22544
  },
  "earnings10": 61945,
  "completion": 0.6881,
  "size": 21217
 },
 {
  "id": 236939,
  "name": "Washington State University",
  "slug": "washington-state-university",
  "city": "Pullman",
  "state": "WA",
  "ownership": "public",
  "sticker": 27648,
  "netPrice": 14971,
  "byIncome": {
   "low": 7074,
   "lowMid": 8971,
   "mid": 11519,
   "upperMid": 18426,
   "high": 24726
  },
  "earnings10": 68905,
  "completion": 0.605,
  "size": 21099
 },
 {
  "id": 228796,
  "name": "The University of Texas at El Paso",
  "slug": "the-university-of-texas-at-el-paso",
  "city": "El Paso",
  "state": "TX",
  "ownership": "public",
  "sticker": 19836,
  "netPrice": 9403,
  "byIncome": {
   "low": 7863,
   "lowMid": 8136,
   "mid": 10120,
   "upperMid": 14093,
   "high": 18282
  },
  "earnings10": 50923,
  "completion": 0.5017,
  "size": 21005
 },
 {
  "id": 216339,
  "name": "Temple University",
  "slug": "temple-university",
  "city": "Philadelphia",
  "state": "PA",
  "ownership": "public",
  "sticker": 40903,
  "netPrice": 28198,
  "byIncome": {
   "low": 22694,
   "lowMid": 23431,
   "mid": 26534,
   "upperMid": 29397,
   "high": 34947
  },
  "earnings10": 63727,
  "completion": 0.7505,
  "size": 20970
 },
 {
  "id": 232423,
  "name": "James Madison University",
  "slug": "james-madison-university",
  "city": "Harrisonburg",
  "state": "VA",
  "ownership": "public",
  "sticker": 31735,
  "netPrice": 23322,
  "byIncome": {
   "low": 11444,
   "lowMid": 12977,
   "mid": 16475,
   "upperMid": 22343,
   "high": 30147
  },
  "earnings10": 69954,
  "completion": 0.7972,
  "size": 20888
 },
 {
  "id": 234030,
  "name": "Virginia Commonwealth University",
  "slug": "virginia-commonwealth-university",
  "city": "Richmond",
  "state": "VA",
  "ownership": "public",
  "sticker": 38954,
  "netPrice": 23433,
  "byIncome": {
   "low": 17512,
   "lowMid": 17777,
   "mid": 20925,
   "upperMid": 24691,
   "high": 32739
  },
  "earnings10": 58128,
  "completion": 0.6318,
  "size": 20753
 },
 {
  "id": 199120,
  "name": "University of North Carolina at Chapel Hill",
  "slug": "university-of-north-carolina-at-chapel-hill",
  "city": "Chapel Hill",
  "state": "NC",
  "ownership": "public",
  "sticker": 26055,
  "netPrice": 11655,
  "byIncome": {
   "low": 2004,
   "lowMid": 3918,
   "mid": 8538,
   "upperMid": 16415,
   "high": 24396
  },
  "earnings10": 72200,
  "completion": 0.9117,
  "size": 20752
 },
 {
  "id": 209551,
  "name": "University of Oregon",
  "slug": "university-of-oregon",
  "city": "Eugene",
  "state": "OR",
  "ownership": "public",
  "sticker": 34793,
  "netPrice": 22182,
  "byIncome": {
   "low": 15909,
   "lowMid": 15760,
   "mid": 18364,
   "upperMid": 24704,
   "high": 31021
  },
  "earnings10": 61324,
  "completion": 0.7169,
  "size": 20497
 },
 {
  "id": 123961,
  "name": "University of Southern California",
  "slug": "university-of-southern-california",
  "city": "Los Angeles",
  "state": "CA",
  "ownership": "private",
  "sticker": 90300,
  "netPrice": 32740,
  "byIncome": {
   "low": 13516,
   "lowMid": 14394,
   "mid": 19539,
   "upperMid": 24976,
   "high": 56116
  },
  "earnings10": 92498,
  "completion": 0.9183,
  "size": 20443
 },
 {
  "id": 215293,
  "name": "University of Pittsburgh-Pittsburgh Campus",
  "slug": "university-of-pittsburgh-pittsburgh-campus",
  "city": "Pittsburgh",
  "state": "PA",
  "ownership": "public",
  "sticker": 38105,
  "netPrice": 30434,
  "byIncome": {
   "low": 14709,
   "lowMid": 18371,
   "mid": 23192,
   "upperMid": 31567,
   "high": 36008
  },
  "earnings10": 66125,
  "completion": 0.855,
  "size": 20370
 },
 {
  "id": 230728,
  "name": "Utah State University",
  "slug": "utah-state-university",
  "city": "Logan",
  "state": "UT",
  "ownership": "public",
  "sticker": 21654,
  "netPrice": 14936,
  "byIncome": {
   "low": 12057,
   "lowMid": 12803,
   "mid": 13521,
   "upperMid": 16094,
   "high": 19169
  },
  "earnings10": 54022,
  "completion": 0.5913,
  "size": 20272
 },
 {
  "id": 196088,
  "name": "University at Buffalo",
  "slug": "university-at-buffalo",
  "city": "Buffalo",
  "state": "NY",
  "ownership": "public",
  "sticker": 30785,
  "netPrice": 20995,
  "byIncome": {
   "low": 14668,
   "lowMid": 16585,
   "mid": 21262,
   "upperMid": 24117,
   "high": 28079
  },
  "earnings10": 70814,
  "completion": 0.7518,
  "size": 20112
 },
 {
  "id": 198464,
  "name": "East Carolina University",
  "slug": "east-carolina-university",
  "city": "Greenville",
  "state": "NC",
  "ownership": "public",
  "sticker": 23867,
  "netPrice": 15739,
  "byIncome": {
   "low": 10046,
   "lowMid": 11699,
   "mid": 14904,
   "upperMid": 20417,
   "high": 23028
  },
  "earnings10": 55146,
  "completion": 0.6262,
  "size": 19896
 },
 {
  "id": 129020,
  "name": "University of Connecticut",
  "slug": "university-of-connecticut",
  "city": "Storrs",
  "state": "CT",
  "ownership": "public",
  "sticker": 39426,
  "netPrice": 25097,
  "byIncome": {
   "low": 15193,
   "lowMid": 16339,
   "mid": 20608,
   "upperMid": 28285,
   "high": 33797
  },
  "earnings10": 73997,
  "completion": 0.8329,
  "size": 19835
 },
 {
  "id": 204857,
  "name": "Ohio University-Main Campus",
  "slug": "ohio-university-main-campus",
  "city": "Athens",
  "state": "OH",
  "ownership": "public",
  "sticker": 30586,
  "netPrice": 21637,
  "byIncome": {
   "low": 15673,
   "lowMid": 15160,
   "mid": 19078,
   "upperMid": 23689,
   "high": 24492
  },
  "earnings10": 52581,
  "completion": 0.6545,
  "size": 19633
 },
 {
  "id": 110592,
  "name": "California State University-Los Angeles",
  "slug": "california-state-university-los-angeles",
  "city": "Los Angeles",
  "state": "CA",
  "ownership": "public",
  "sticker": 18403,
  "netPrice": 3967,
  "byIncome": {
   "low": 2877,
   "lowMid": 2974,
   "mid": 5002,
   "upperMid": 7355,
   "high": 13578
  },
  "earnings10": 59211,
  "completion": 0.5298,
  "size": 19562
 },
 {
  "id": 197869,
  "name": "Appalachian State University",
  "slug": "appalachian-state-university",
  "city": "Boone",
  "state": "NC",
  "ownership": "public",
  "sticker": 23169,
  "netPrice": 16836,
  "byIncome": {
   "low": 9325,
   "lowMid": 11600,
   "mid": 15204,
   "upperMid": 20840,
   "high": 22382
  },
  "earnings10": 51836,
  "completion": 0.7453,
  "size": 19444
 },
 {
  "id": 203517,
  "name": "Kent State University at Kent",
  "slug": "kent-state-university-at-kent",
  "city": "Kent",
  "state": "OH",
  "ownership": "public",
  "sticker": 30567,
  "netPrice": 20787,
  "byIncome": {
   "low": 15280,
   "lowMid": 15718,
   "mid": 17296,
   "upperMid": 23685,
   "high": 26278
  },
  "earnings10": 45388,
  "completion": 0.6372,
  "size": 19320
 },
 {
  "id": 181464,
  "name": "University of Nebraska-Lincoln",
  "slug": "university-of-nebraska-lincoln",
  "city": "Lincoln",
  "state": "NE",
  "ownership": "public",
  "sticker": 26697,
  "netPrice": 17747,
  "byIncome": {
   "low": 12751,
   "lowMid": 13054,
   "mid": 14699,
   "upperMid": 18975,
   "high": 22346
  },
  "earnings10": 56887,
  "completion": 0.6697,
  "size": 19178
 },
 {
  "id": 130943,
  "name": "University of Delaware",
  "slug": "university-of-delaware",
  "city": "Newark",
  "state": "DE",
  "ownership": "public",
  "sticker": 30952,
  "netPrice": 17799,
  "byIncome": {
   "low": 10901,
   "lowMid": 10099,
   "mid": 13225,
   "upperMid": 17401,
   "high": 25580
  },
  "earnings10": 72950,
  "completion": 0.8055,
  "size": 19071
 },
 {
  "id": 145813,
  "name": "Illinois State University",
  "slug": "illinois-state-university",
  "city": "Normal",
  "state": "IL",
  "ownership": "public",
  "sticker": 34309,
  "netPrice": 19398,
  "byIncome": {
   "low": 11568,
   "lowMid": 12301,
   "mid": 16348,
   "upperMid": 23865,
   "high": 28224
  },
  "earnings10": 62117,
  "completion": 0.6454,
  "size": 19057
 },
 {
  "id": 170082,
  "name": "Grand Valley State University",
  "slug": "grand-valley-state-university",
  "city": "Allendale",
  "state": "MI",
  "ownership": "public",
  "sticker": 28367,
  "netPrice": 16317,
  "byIncome": {
   "low": 12272,
   "lowMid": 11902,
   "mid": 12861,
   "upperMid": 16609,
   "high": 22534
  },
  "earnings10": 56118,
  "completion": 0.6701,
  "size": 18854
 },
 {
  "id": 139755,
  "name": "Georgia Institute of Technology-Main Campus",
  "slug": "georgia-institute-of-technology-main-campus",
  "city": "Atlanta",
  "state": "GA",
  "ownership": "public",
  "sticker": 28167,
  "netPrice": 12116,
  "byIncome": {
   "low": 7666,
   "lowMid": 7209,
   "mid": 10818,
   "upperMid": 15088,
   "high": 17396
  },
  "earnings10": 102772,
  "completion": 0.9402,
  "size": 18785
 },
 {
  "id": 122597,
  "name": "San Francisco State University",
  "slug": "san-francisco-state-university",
  "city": "San Francisco",
  "state": "CA",
  "ownership": "public",
  "sticker": 26488,
  "netPrice": 12278,
  "byIncome": {
   "low": 9341,
   "lowMid": 9867,
   "mid": 11825,
   "upperMid": 14556,
   "high": 22523
  },
  "earnings10": 68077,
  "completion": 0.5037,
  "size": 18639
 },
 {
  "id": 176080,
  "name": "Mississippi State University",
  "slug": "mississippi-state-university",
  "city": "Mississippi State",
  "state": "MS",
  "ownership": "public",
  "sticker": 29267,
  "netPrice": 17595,
  "byIncome": {
   "low": 14332,
   "lowMid": 14372,
   "mid": 18671,
   "upperMid": 20704,
   "high": 22987
  },
  "earnings10": 51513,
  "completion": 0.6667,
  "size": 18397
 },
 {
  "id": 185590,
  "name": "Montclair State University",
  "slug": "montclair-state-university",
  "city": "Montclair",
  "state": "NJ",
  "ownership": "public",
  "sticker": 28305,
  "netPrice": 15566,
  "byIncome": {
   "low": 10880,
   "lowMid": 11532,
   "mid": 16388,
   "upperMid": 22058,
   "high": 25573
  },
  "earnings10": 61415,
  "completion": 0.6466,
  "size": 18376
 },
 {
  "id": 413413,
  "name": "Capella University",
  "slug": "capella-university",
  "city": "Minneapolis",
  "state": "MN",
  "ownership": "for-profit",
  "sticker": 22820,
  "netPrice": 17956,
  "byIncome": {
   "low": 17485,
   "lowMid": 17324,
   "mid": 17490,
   "upperMid": 21292,
   "high": 22820
  },
  "earnings10": 42189,
  "completion": 0.2,
  "size": 18364
 },
 {
  "id": 164988,
  "name": "Boston University",
  "slug": "boston-university",
  "city": "Boston",
  "state": "MA",
  "ownership": "private",
  "sticker": 86285,
  "netPrice": 24402,
  "byIncome": {
   "low": 9500,
   "lowMid": 9342,
   "mid": 11778,
   "upperMid": 22517,
   "high": 47504
  },
  "earnings10": 83238,
  "completion": 0.8866,
  "size": 18248
 },
 {
  "id": 196097,
  "name": "Stony Brook University",
  "slug": "stony-brook-university",
  "city": "Stony Brook",
  "state": "NY",
  "ownership": "public",
  "sticker": 30539,
  "netPrice": 18784,
  "byIncome": {
   "low": 12943,
   "lowMid": 15432,
   "mid": 20728,
   "upperMid": 23424,
   "high": 27716
  },
  "earnings10": 74502,
  "completion": 0.7556,
  "size": 18101
 },
 {
  "id": 110714,
  "name": "University of California-Santa Cruz",
  "slug": "university-of-california-santa-cruz",
  "city": "Santa Cruz",
  "state": "CA",
  "ownership": "public",
  "sticker": 41179,
  "netPrice": 17890,
  "byIncome": {
   "low": 8717,
   "lowMid": 10613,
   "mid": 14418,
   "upperMid": 18986,
   "high": 33323
  },
  "earnings10": 68396,
  "completion": 0.7509,
  "size": 17940
 },
 {
  "id": 227881,
  "name": "Sam Houston State University",
  "slug": "sam-houston-state-university",
  "city": "Huntsville",
  "state": "TX",
  "ownership": "public",
  "sticker": 25505,
  "netPrice": 16404,
  "byIncome": {
   "low": 12474,
   "lowMid": 13389,
   "mid": 15540,
   "upperMid": 21366,
   "high": 24101
  },
  "earnings10": 54211,
  "completion": 0.5476,
  "size": 17743
 },
 {
  "id": 142115,
  "name": "Boise State University",
  "slug": "boise-state-university",
  "city": "Boise",
  "state": "ID",
  "ownership": "public",
  "sticker": 28224,
  "netPrice": 21610,
  "byIncome": {
   "low": 18165,
   "lowMid": 17974,
   "mid": 20731,
   "upperMid": 23573,
   "high": 25893
  },
  "earnings10": 51658,
  "completion": 0.602,
  "size": 17674
 },
 {
  "id": 234076,
  "name": "University of Virginia-Main Campus",
  "slug": "university-of-virginia-main-campus",
  "city": "Charlottesville",
  "state": "VA",
  "ownership": "public",
  "sticker": 39926,
  "netPrice": 21565,
  "byIncome": {
   "low": 8174,
   "lowMid": 9696,
   "mid": 13283,
   "upperMid": 20822,
   "high": 35402
  },
  "earnings10": 86863,
  "completion": 0.956,
  "size": 17597
 },
 {
  "id": 232982,
  "name": "Old Dominion University",
  "slug": "old-dominion-university",
  "city": "Norfolk",
  "state": "VA",
  "ownership": "public",
  "sticker": 29446,
  "netPrice": 14638,
  "byIncome": {
   "low": 9739,
   "lowMid": 10114,
   "mid": 13123,
   "upperMid": 16940,
   "high": 23567
  },
  "earnings10": 54914,
  "completion": 0.4632,
  "size": 17514
 },
 {
  "id": 238032,
  "name": "West Virginia University",
  "slug": "west-virginia-university",
  "city": "Morgantown",
  "state": "WV",
  "ownership": "public",
  "sticker": 26415,
  "netPrice": 15634,
  "byIncome": {
   "low": 9450,
   "lowMid": 12501,
   "mid": 14179,
   "upperMid": 18710,
   "high": 20273
  },
  "earnings10": 55939,
  "completion": 0.6466,
  "size": 17385
 },
 {
  "id": 167358,
  "name": "Northeastern University",
  "slug": "northeastern-university",
  "city": "Boston",
  "state": "MA",
  "ownership": "private",
  "sticker": 84641,
  "netPrice": 30915,
  "byIncome": {
   "low": 2264,
   "lowMid": 2436,
   "mid": 5301,
   "upperMid": 16241,
   "high": 47696
  },
  "earnings10": 92538,
  "completion": 0.9054,
  "size": 17326
 },
 {
  "id": 187985,
  "name": "University of New Mexico-Main Campus",
  "slug": "university-of-new-mexico-main-campus",
  "city": "Albuquerque",
  "state": "NM",
  "ownership": "public",
  "sticker": 21259,
  "netPrice": 15489,
  "byIncome": {
   "low": 11938,
   "lowMid": 13045,
   "mid": 16196,
   "upperMid": 17906,
   "high": 19053
  },
  "earnings10": 44792,
  "completion": 0.5469,
  "size": 17244
 },
 {
  "id": 240453,
  "name": "University of Wisconsin-Milwaukee",
  "slug": "university-of-wisconsin-milwaukee",
  "city": "Milwaukee",
  "state": "WI",
  "ownership": "public",
  "sticker": 22756,
  "netPrice": 15014,
  "byIncome": {
   "low": 10329,
   "lowMid": 10709,
   "mid": 12344,
   "upperMid": 19315,
   "high": 21477
  },
  "earnings10": 54990,
  "completion": 0.4932,
  "size": 16758
 },
 {
  "id": 204024,
  "name": "Miami University-Oxford",
  "slug": "miami-university-oxford",
  "city": "Oxford",
  "state": "OH",
  "ownership": "public",
  "sticker": 38757,
  "netPrice": 28384,
  "byIncome": {
   "low": 16015,
   "lowMid": 18193,
   "mid": 23806,
   "upperMid": 29048,
   "high": 31431
  },
  "earnings10": 55076,
  "completion": 0.7979,
  "size": 16656
 },
 {
  "id": 220978,
  "name": "Middle Tennessee State University",
  "slug": "middle-tennessee-state-university",
  "city": "Murfreesboro",
  "state": "TN",
  "ownership": "public",
  "sticker": 24289,
  "netPrice": 13359,
  "byIncome": {
   "low": 9289,
   "lowMid": 10273,
   "mid": 13007,
   "upperMid": 16935,
   "high": 19046
  },
  "earnings10": 48541,
  "completion": 0.537,
  "size": 16301
 },
 {
  "id": 190594,
  "name": "CUNY Hunter College",
  "slug": "cuny-hunter-college",
  "city": "New York",
  "state": "NY",
  "ownership": "public",
  "sticker": 13905,
  "netPrice": 2984,
  "byIncome": {
   "low": 1029,
   "lowMid": 1935,
   "mid": 6003,
   "upperMid": 8810,
   "high": 12259
  },
  "earnings10": 63163,
  "completion": 0.5686,
  "size": 16289
 },
 {
  "id": 190512,
  "name": "CUNY Bernard M Baruch College",
  "slug": "cuny-bernard-m-baruch-college",
  "city": "New York",
  "state": "NY",
  "ownership": "public",
  "sticker": 14170,
  "netPrice": 3033,
  "byIncome": {
   "low": 607,
   "lowMid": 2052,
   "mid": 6312,
   "upperMid": 8623,
   "high": 12314
  },
  "earnings10": 75971,
  "completion": 0.7212,
  "size": 16154
 },
 {
  "id": 482680,
  "name": "University of North Georgia",
  "slug": "university-of-north-georgia",
  "city": "Dahlonega",
  "state": "GA",
  "ownership": "public",
  "sticker": 18177,
  "netPrice": 9823,
  "byIncome": {
   "low": 6981,
   "lowMid": 7261,
   "mid": 10118,
   "upperMid": 12059,
   "high": 13481
  },
  "earnings10": 50135,
  "completion": 0.3729,
  "size": 16146
 },
 {
  "id": 164076,
  "name": "Towson University",
  "slug": "towson-university",
  "city": "Towson",
  "state": "MD",
  "ownership": "public",
  "sticker": 28535,
  "netPrice": 17413,
  "byIncome": {
   "low": 6962,
   "lowMid": 12590,
   "mid": 16784,
   "upperMid": 22720,
   "high": 26396
  },
  "earnings10": 64390,
  "completion": 0.6946,
  "size": 16136
 },
 {
  "id": 190415,
  "name": "Cornell University",
  "slug": "cornell-university",
  "city": "Ithaca",
  "state": "NY",
  "ownership": "private",
  "sticker": 88140,
  "netPrice": 28690,
  "byIncome": {
   "low": 1776,
   "lowMid": 4070,
   "mid": 6796,
   "upperMid": 14311,
   "high": 49992
  },
  "earnings10": 104043,
  "completion": 0.9538,
  "size": 15995
 },
 {
  "id": 184782,
  "name": "Rowan University",
  "slug": "rowan-university",
  "city": "Glassboro",
  "state": "NJ",
  "ownership": "public",
  "sticker": 35842,
  "netPrice": 22408,
  "byIncome": {
   "low": 15305,
   "lowMid": 15264,
   "mid": 19245,
   "upperMid": 27580,
   "high": 30378
  },
  "earnings10": 59988,
  "completion": 0.6736,
  "size": 15841
 },
 {
  "id": 182290,
  "name": "University of Nevada-Reno",
  "slug": "university-of-nevada-reno",
  "city": "Reno",
  "state": "NV",
  "ownership": "public",
  "sticker": 25786,
  "netPrice": 15927,
  "byIncome": {
   "low": 12674,
   "lowMid": 13125,
   "mid": 14537,
   "upperMid": 18317,
   "high": 21646
  },
  "earnings10": 60614,
  "completion": 0.6124,
  "size": 15599
 },
 {
  "id": 172644,
  "name": "Wayne State University",
  "slug": "wayne-state-university",
  "city": "Detroit",
  "state": "MI",
  "ownership": "public",
  "sticker": 27350,
  "netPrice": 12766,
  "byIncome": {
   "low": 11090,
   "lowMid": 10721,
   "mid": 12068,
   "upperMid": 14828,
   "high": 19862
  },
  "earnings10": 53493,
  "completion": 0.5844,
  "size": 15587
 },
 {
  "id": 196413,
  "name": "Syracuse University",
  "slug": "syracuse-university",
  "city": "Syracuse",
  "state": "NY",
  "ownership": "private",
  "sticker": 84517,
  "netPrice": 38793,
  "byIncome": {
   "low": 15817,
   "lowMid": 15845,
   "mid": 21132,
   "upperMid": 28780,
   "high": 55401
  },
  "earnings10": 79164,
  "completion": 0.8361,
  "size": 15477
 },
 {
  "id": 140951,
  "name": "Savannah College of Art and Design",
  "slug": "savannah-college-of-art-and-design",
  "city": "Savannah",
  "state": "GA",
  "ownership": "private",
  "sticker": 63627,
  "netPrice": 49430,
  "byIncome": {
   "low": 44858,
   "lowMid": 45198,
   "mid": 48668,
   "upperMid": 51558,
   "high": 52147
  },
  "earnings10": 45954,
  "completion": 0.6941,
  "size": 15243
 },
 {
  "id": 155399,
  "name": "Kansas State University",
  "slug": "kansas-state-university",
  "city": "Manhattan",
  "state": "KS",
  "ownership": "public",
  "sticker": 27402,
  "netPrice": 19406,
  "byIncome": {
   "low": 13178,
   "lowMid": 14143,
   "mid": 15369,
   "upperMid": 20110,
   "high": 23665
  },
  "earnings10": 57262,
  "completion": 0.7108,
  "size": 15142
 },
 {
  "id": 141574,
  "name": "University of Hawaii at Manoa",
  "slug": "university-of-hawaii-at-manoa",
  "city": "Honolulu",
  "state": "HI",
  "ownership": "public",
  "sticker": 26433,
  "netPrice": 15664,
  "byIncome": {
   "low": 10675,
   "lowMid": 12246,
   "mid": 14469,
   "upperMid": 18760,
   "high": 22562
  },
  "earnings10": 57624,
  "completion": 0.6429,
  "size": 15029
 },
 {
  "id": 110510,
  "name": "California State University-San Bernardino",
  "slug": "california-state-university-san-bernardino",
  "city": "San Bernardino",
  "state": "CA",
  "ownership": "public",
  "sticker": 17427,
  "netPrice": 4564,
  "byIncome": {
   "low": 2681,
   "lowMid": 2680,
   "mid": 4735,
   "upperMid": 7745,
   "high": 14316
  },
  "earnings10": 59977,
  "completion": 0.549,
  "size": 15023
 },
 {
  "id": 127565,
  "name": "Metropolitan State University of Denver",
  "slug": "metropolitan-state-university-of-denver",
  "city": "Denver",
  "state": "CO",
  "ownership": "public",
  "sticker": 24622,
  "netPrice": 15327,
  "byIncome": {
   "low": 12481,
   "lowMid": 12436,
   "mid": 14927,
   "upperMid": 19539,
   "high": 23822
  },
  "earnings10": 52093,
  "completion": 0.3154,
  "size": 15002
 }
];

export const collegeBySlug = (s: string): College | undefined =>
  COLLEGES.find((c) => c.slug === s);
